// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PartsPractice.Models.DataLayer;

namespace PartsPractice.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210711091855_Whole-Sale-Price")]
    partial class WholeSalePrice
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PartsPractice.Models.Parts", b =>
                {
                    b.Property<long>("PartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Available")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("QtyOnHand")
                        .HasColumnType("int");

                    b.Property<decimal>("WholeSalePrice")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("PartId");

                    b.ToTable("PartsItems");

                    b.HasData(
                        new
                        {
                            PartId = 1L,
                            Available = true,
                            Description = "Ball pein Hammer",
                            Name = "Hammer",
                            Price = 44.44m,
                            QtyOnHand = 100,
                            WholeSalePrice = 0m
                        },
                        new
                        {
                            PartId = 2L,
                            Available = true,
                            Description = "Flat head",
                            Name = "ScrewDriver",
                            Price = 10.44m,
                            QtyOnHand = 50,
                            WholeSalePrice = 0m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
